version: '3'
services:
  grafana8:
      image: grafana/grafana:8.4.4
      network_mode: "host"
      user: root
      volumes:
        - ./grafana_data:/var/lib/grafana:rw
      ports:
        - "3000:3000"
      environment:
        - GF_SERVER_ROOT_URL=http://192.168.1.22:3000
      restart: always 

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - type: bind
        source: ./loki-config.yaml
        target: /etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    
  promtail:
    image: grafana/promtail:2.8.2
    user: root
    network_mode: "host"
    container_name: promtail
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./promtail-config.yaml
        target: /etc/promtail/promtail-config.yaml
      - type: bind
        source: /var/log
        target: /var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml
     
  logtest:
    image: docker.com/users/hj/logtest:0.1
    container_name: logtest
    network_mode: "host"
    restart: unless-stopped
    labels:
          - "logging=promtail"
          - "logging_jobname=logtest"    

